version: "3"

services:

  radius-mysql:
    image: mariadb:10
    container_name: radius-mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - "./data/mysql:/var/lib/mysql"

  radius:
    container_name: radius
    build:
      context: .
      dockerfile: Dockerfile-freeradius
    restart: unless-stopped
    depends_on:
      - radius-mysql
    ports:
      - '${RADIUS_AUTH_PORT}:1812/udp'
      - '${RADIUS_ACCT_PORT}:1813/udp'
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - DEFAULT_CLIENT_SECRET=${DEFAULT_CLIENT_SECRET}
#    volumes:
#      - ./data/freeradius:/data
    # If you want to disable debug output, remove the command parameter
    command: -X

  radius-web:
    build: .
    container_name: radius-web
    restart: unless-stopped
    depends_on:
      - radius
      - radius-mysql
    ports:
      #- '80:80'
      - '${WEB_PORT}:8000'
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - DEFAULT_CLIENT_SECRET=${DEFAULT_CLIENT_SECRET}
      - DEFAULT_FREERADIUS_SERVER=${DEFAULT_FREERADIUS_SERVER}
      - MAIL_SMTPADDR=${MAIL_SMTPADDR}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_AUTH=${MAIL_AUTH}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_ENABLED=${MAIL_ENABLED}
      - MAIL_SMTP_SECURITY=${MAIL_SMTP_SECURITY}
      - MAIL_SMTP_SENDER_NAME=${MAIL_SMTP_SENDER_NAME}
      - MAIL_SMTP_SUBJECT_PREFIX=${MAIL_SMTP_SUBJECT_PREFIX}
      - MAIL_SMTP_USERNAME=${MAIL_SMTP_USERNAME}
      - MAIL_SMTP_PASSWORD=${MAIL_SMTP_PASSWORD}
      - USER_VPN_SERVER=${USER_VPN_SERVER}

    volumes:
      - ./data/daloradius:/data
