version: "3"

services:

  radius-mysql:
    image: mariadb:10
    container_name: radius-mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - "./data/mysql:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 30s

  radius:
    container_name: radius
    build:
      context: .
      dockerfile: Dockerfile-freeradius
    restart: unless-stopped
    depends_on:
      radius-mysql:
        condition: service_healthy
    ports:
      - '${RADIUS_AUTH_PORT}:1812/udp'
      - '${RADIUS_ACCT_PORT}:1813/udp'
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - DEFAULT_CLIENT_SECRET=${DEFAULT_CLIENT_SECRET}
      - RADIUS_CERT_DIR=/opt/radius-certs
      - RADIUS_DEFAULT_EAP_TYPE=${RADIUS_DEFAULT_EAP_TYPE:-peap}
    volumes:
      - ${RADIUS_CERT_HOST_DIR:-/opt/radius-certs}:/opt/radius-certs:ro
#      - ./data/freeradius:/data
    # If you want to disable debug output, remove the command parameter
    command: -X

  radius-web:
    build: .
    container_name: radius-web
    restart: unless-stopped
    depends_on:
      radius:
        condition: service_started
      radius-mysql:
        condition: service_healthy
    ports:
      #- '80:80'
      - '${WEB_PORT}:8000'
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DEFAULT_CLIENT_SECRET=${DEFAULT_CLIENT_SECRET}
      - DEFAULT_FREERADIUS_SERVER=${DEFAULT_FREERADIUS_SERVER}
      - MAIL_SMTPADDR=${MAIL_SMTPADDR}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_AUTH=${MAIL_AUTH}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_ENABLED=${MAIL_ENABLED}
      - MAIL_SMTP_SECURITY=${MAIL_SMTP_SECURITY}
      - MAIL_SMTP_SENDER_NAME=${MAIL_SMTP_SENDER_NAME}
      - MAIL_SMTP_SUBJECT_PREFIX=${MAIL_SMTP_SUBJECT_PREFIX}
      - MAIL_SMTP_USERNAME=${MAIL_SMTP_USERNAME}
      - MAIL_SMTP_PASSWORD=${MAIL_SMTP_PASSWORD}
      - MAIL_BODY_NOTE=${MAIL_BODY_NOTE}
      - USER_VPN_SERVER=${USER_VPN_SERVER}

    volumes:
      - ./data/daloradius:/data
